language: cpp

os:
  - osx
  - linux

compiler:
  - clang
  - gcc

env:
  global:
    - export FC="gfortran"

before_install:
  # gcc/g++ 4.8.1, clang/clang++ 3.4 and gfortran 4.8
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; 
      sudo add-apt-repository -y ppa:h-rayflood/llvm; 
      sudo apt-get update -qq;
    fi

install:
  - sudo apt-get install -qq bc

  # gfortran 4.8
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      sudo apt-get install -qq gfortran-4.8;
      sudo update-alternatives
           --install /usr/bin/gfortran gfortran /usr/bin/gfortran-4.8 90;
    fi

  # gcc/g++ 4.8.1
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      sudo apt-get install -qq g++-4.8;
      sudo update-alternatives
           --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90;
      sudo update-alternatives
           --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90;
    fi

  # clang/clang++ 3.4
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then 
      sudo apt-get install --allow-unauthenticated -qq clang-3.4;
      sudo update-alternatives
           --install /usr/bin/clang clang /usr/bin/clang-3.4 90;
      sudo update-alternatives
           --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.4 90;
    fi

script:
  - ./test/tests.sh
